import tailwindcss from "@tailwindcss/vite";
import react from "@vitejs/plugin-react";
import { defineConfig } from "vite";

/**
 * The API runs as a separate process on 3000. Proxying /api and /health here
 * means the browser only ever talks to one origin, so there is no CORS story
 * to debug in development and no base URL to configure in the client.
 */
const API_ORIGIN = "http://localhost:3000";

export default defineConfig({
  plugins: [react(), tailwindcss()],
  server: {
    port: 5173,
    proxy: {
      "/api": { target: API_ORIGIN, changeOrigin: true },
      "/health": { target: API_ORIGIN, changeOrigin: true },
    },
  },
  build: {
    outDir: "dist",
    sourcemap: true,
    /**
     * The offline dataset rides in the main chunk on purpose, and it is why this
     * limit is raised a little rather than why the bundle should be split.
     *
     * `src/lib/mock-data.ts` is the company the API serves, generated by
     * `bun run web:mock`: 44 suppliers, 92 instructions, and the 156 invoices of
     * the company's 4103 that a screen can reach. A dynamic import would move it
     * out of the warning and into a second HTTP request, and this is the data the
     * app falls back to when there is no API to request anything from, so a code
     * split would make it unavailable exactly when it is needed.
     *
     * The bundle is 565 KB, 160 KB gzipped, which is over Rollup's 500 KB default
     * and a long way under what it was: carrying all 4103 invoices made it 1757 KB
     * and 359 KB gzipped, for an eight-month history no screen of this app opens.
     * 700 is headroom for a screen, not for the whole history coming back.
     */
    chunkSizeWarningLimit: 700,
  },
});
