/**
 * Names and addresses for synthetic customers.
 *
 * Every person generated by this package is invented. The colonias and avenues are
 * real places in Monterrey, used so an address looks like an address; the street
 * numbers are random and no combination here is anybody's home.
 *
 * No real person's data is in this repo, which is the whole posture in SECURITY.md:
 * synthetic data only, so a leaked dump leaks nothing.
 */

export const MX_FIRST_NAMES: readonly string[] = [
  "Ximena",
  "Rodrigo",
  "Valeria",
  "Emiliano",
  "Regina",
  "Santiago",
  "Mariana",
  "Sebastian",
  "Renata",
  "Diego",
  "Fernanda",
  "Alejandro",
  "Camila",
  "Patricio",
  "Andrea",
  "Gerardo",
];

export const MX_LAST_NAMES: readonly string[] = [
  "Trevino",
  "Cantu",
  "Garza",
  "Villarreal",
  "Elizondo",
  "Zambrano",
  "Gonzalez",
  "Salinas",
  "De la Garza",
  "Guerra",
  "Leal",
  "Rodriguez",
  "Ayala",
  "Ramos",
];

export interface Colonia {
  /** A real avenue or street in that colonia. */
  streetName: string;
  colonia: string;
  zip: string;
}

export const MTY_COLONIAS: readonly Colonia[] = [
  {
    streetName: "Avenida Eugenio Garza Sada",
    colonia: "Tecnologico",
    zip: "64849",
  },
  {
    streetName: "Avenida Lazaro Cardenas",
    colonia: "Valle Oriente",
    zip: "66269",
  },
  { streetName: "Avenida Gonzalitos", colonia: "Mitras Centro", zip: "64460" },
  { streetName: "Avenida Leones", colonia: "Cumbres", zip: "64610" },
  { streetName: "Calzada San Pedro", colonia: "Del Valle", zip: "66220" },
  { streetName: "Avenida Revolucion", colonia: "Contry", zip: "64860" },
  { streetName: "Avenida Ruiz Cortines", colonia: "Anahuac", zip: "66450" },
  { streetName: "Avenida Hidalgo", colonia: "Obispado", zip: "64060" },
];

export const MX_STATE = "NL";
export const MX_CITY = "Monterrey";

export interface AccountFlavour {
  type: string;
  nickname: string;
}

/** Nessie account types, with nicknames a person would actually use. */
export const ACCOUNT_FLAVOURS: readonly AccountFlavour[] = [
  { type: "Checking", nickname: "Gastos diarios" },
  { type: "Savings", nickname: "Ahorro quincena" },
];
