/**
 * The assistant panel with no API behind it.
 *
 * The panel has to be demonstrable on a phone in a corridor, under `?data=mock`,
 * where the documented promise is that no request leaves the browser. So there is
 * no model here, and the first thing this module does is refuse to pretend there
 * is one: every sentence it produces is assembled out of the synthetic run in
 * `./mock-data.ts`, the panel says so in its header, and nothing below asserts a
 * fact the deterministic side did not already compute.
 *
 * That is not a smaller version of the feature, it is the honest one. What the
 * judges are told the panel does is read what the engine computed, answer in
 * Spanish and offer one action a person executes. Offline, the reading is real
 * (the findings, the totals, the verification and the supplier's own accounts are
 * the generated company's own rows), the answer is assembled from those rows, and
 * the proposal is the same `ActionProposal` the API would send. The part that is
 * missing is the language, and the header says which part that is.
 *
 * Three rows of the generated dataset are read straight from `./mock-data.ts`
 * rather than through `./mock.ts`: the conversation, the actor and the execution.
 * `./mock.ts` exists to compose the payloads the API assembles out of several
 * rows, and these three are already payloads: `ASSISTANT_SESSION` is what
 * `GET /api/v1/assistant/sessions/:id` answers, `ACTOR` is the person every write
 * carries on `X-Actor`, and `EXECUTION` is what the run did on the rail.
 *
 * `assistant.test.ts` drives every branch below with a fixed timestamp, so the
 * offline turn is a pure function of the run and the question: same question, same
 * answer, no clock and no network.
 */

import type {
  ActionProposal,
  Actor,
  AssistantMessage,
  AssistantSession,
  AssistantToolCall,
  Confidence,
  EvidenceValue,
  Finding,
  TransactionState,
} from "@hackmty/core";
import {
  assessConfidence,
  executionLineOf,
  transactionStateOf,
} from "@hackmty/core";
import type {
  AssistantImage,
  AssistantStreamEvent,
  InstructionDetail,
  PaymentRunItem,
  VerificationState,
} from "./contract";
import { formatClabe, formatMoney } from "./format";
import { CONFIDENCE_LABEL, STATE_LABEL, VERIFICATION_LABEL } from "./labels";
import {
  DEMO_INSTRUCTION_IDS,
  MOCK_RUN,
  mockInstruction,
  mockIntakeExample,
  mockVerification,
  RUN_ITEMS,
} from "./mock";
import { ACTOR, ASSISTANT_SESSION, EXECUTION } from "./mock-data";

/** The person the offline panel acts as, and the name a write would carry. */
export const MOCK_ACTOR: Actor = ACTOR;

/**
 * The conversation the panel opens with offline: three turns about the line the
 * demo opens on, generated by `bun run web:mock` out of that line's own finding.
 */
export function mockAssistantSession(): AssistantSession {
  return ASSISTANT_SESSION;
}

/** The line a question with no folio in it is about. */
export function defaultInstructionId(): string {
  return DEMO_INSTRUCTION_IDS[0] ?? RUN_ITEMS[0]?.instruction.id ?? "";
}

const FOLIO = /INS-\d{4}-\d{2}-\d{2}-\d{3}/i;

/** The folio the clerk typed, when the run actually holds that line. */
export function folioIn(text: string): string | null {
  const found = FOLIO.exec(text)?.[0]?.toUpperCase() ?? null;

  return found !== null && mockInstruction(found) !== null ? found : null;
}

/* ------------------------------------------------------- level and state --- */

export interface LineLevel {
  confidence: Confidence;
  state: TransactionState;
  /** The findings the level was computed from, which is how it is shown. */
  findingIds: string[];
}

/**
 * The level and the state of one line, derived here by the same two pure
 * functions the API calls.
 *
 * `LEVELS_BY_INSTRUCTION` in the generated file carries exactly this, and it is
 * deliberately not read: a decision applied in the browser moves the level, and a
 * stored one would then disagree with the findings under it. That is the argument
 * ADR-0009 makes for never storing either value, applied to the one place that
 * could have cached it.
 */
export function levelOf(item: PaymentRunItem): LineLevel {
  const assessment = assessConfidence(item.findings, item.decision);
  const verification = mockVerification(item.instruction.id);

  return {
    confidence: assessment.level,
    state: transactionStateOf(
      { ...item.decision, findings: item.findings },
      verification,
      executionLineOf(EXECUTION, item.instruction.id),
    ),
    findingIds: assessment.findingIds,
  };
}

/* ------------------------------------------------------------ the answers --- */

/** The finding that stopped a line: the most pesos at risk wins. */
function leadFinding(item: PaymentRunItem): Finding | null {
  return (
    [...item.findings].sort(
      (left, right) => right.amountAtRisk - left.amountAtRisk,
    )[0] ?? null
  );
}

/** Only primitives reach a tool result, which is what the chips can render. */
function primitives(
  evidence: Readonly<Record<string, EvidenceValue>>,
): Record<string, EvidenceValue> {
  return Object.fromEntries(
    Object.entries(evidence).filter(([, value]) => typeof value !== "object"),
  );
}

function lastFour(clabe: string): string {
  return clabe.slice(-4);
}

export interface OfflineTurnInput {
  text: string;
  images: readonly AssistantImage[];
  sessionId: string;
  /** The instant the turn is stamped with. Passed in, so a test is exact. */
  at: string;
  /** Which turn of the conversation this is, for the ids. */
  seq: number;
  /** The line the panel has open, when it has one. */
  instructionId?: string | null;
}

interface Answer {
  text: string;
  toolCalls: AssistantToolCall[];
  proposal?: ActionProposal;
  instructionId?: string;
}

/**
 * What the panel answers with no API, for the question it was asked.
 *
 * The branches are the three quick prompts plus the two the demo needs: a dropped
 * screenshot and the state of a verification. Anything else is answered by saying
 * what this panel can read offline, which is a better answer than a sentence
 * invented to look like an answer.
 */
function answerFor(input: OfflineTurnInput): Answer {
  const lowered = input.text.toLowerCase();
  const id =
    folioIn(input.text) ?? input.instructionId ?? defaultInstructionId();
  const item = mockInstruction(id);

  if (input.images.length > 0) {
    return intakeAnswer();
  }

  if (item === null) {
    return helpAnswer();
  }

  if (/resumen|semana|dueno|dueño|corrida completa/.test(lowered)) {
    return runAnswer(input);
  }

  if (/historial|proveedor|cuenta conocida|ya le pag/.test(lowered)) {
    return supplierAnswer(item, input);
  }

  if (/verificaci|centavo|cep|sello/.test(lowered)) {
    return verificationAnswer(item, input);
  }

  if (/liberar|libera|autoriz/.test(lowered)) {
    return releaseAnswer(item, input);
  }

  return whyAnswer(item, input);
}

function toolCall(
  input: OfflineTurnInput,
  index: number,
  tool: AssistantToolCall["tool"],
  args: Record<string, string | number | boolean>,
  result: Record<string, EvidenceValue>,
): AssistantToolCall {
  return {
    id: `${input.sessionId}-${input.seq}-tool-${index}`,
    tool,
    arguments: args,
    result,
    at: input.at,
    readOnly: true,
  };
}

/** Why the line is stopped: the engine's own explanation, then level and state. */
function whyAnswer(item: PaymentRunItem, input: OfflineTurnInput): Answer {
  const finding = leadFinding(item);
  const level = levelOf(item);
  const verdict = `El nivel de esta linea es ${CONFIDENCE_LABEL[
    level.confidence
  ].toLowerCase()} y su estado es ${STATE_LABEL[level.state].toLowerCase()}.`;

  if (finding === null) {
    return {
      text: `Los seis controles corrieron sobre ${item.instruction.id} y ninguno encontro nada que revisar. ${verdict}`,
      toolCalls: [
        toolCall(
          input,
          1,
          "get_instruction",
          { instructionId: item.instruction.id },
          {
            amount: item.instruction.amount,
            clabe: item.instruction.clabe,
            hallazgos: 0,
          },
        ),
      ],
      instructionId: item.instruction.id,
    };
  }

  const verification = mockVerification(item.instruction.id);
  const canProbe =
    verification === null || verification.state === "not_started";

  /**
   * A line whose cent has already gone out is not offered the cent again.
   *
   * This is the case the demo folio `INS-2026-09-07-029` is in: the probe left and
   * Banxico has not published the CEP yet. Proposing the verification a second
   * time would be the panel offering to do something that is already done, so the
   * answer says where it stands and carries no proposal at all.
   */
  const standing =
    verification === null || canProbe
      ? ""
      : ` La verificacion de esta cuenta esta en "${VERIFICATION_LABEL[
          verification.state
        ].toLowerCase()}"${
          verification.claveRastreo === null
            ? ""
            : `, con la clave de rastreo ${verification.claveRastreo}`
        }.`;

  const answer: Answer = {
    text: `${finding.explanation} ${verdict}${standing}`,
    toolCalls: [
      toolCall(
        input,
        1,
        "get_instruction",
        { instructionId: item.instruction.id },
        primitives(finding.evidence),
      ),
    ],
    instructionId: item.instruction.id,
  };

  if (canProbe) {
    answer.proposal = {
      kind: "verify_account",
      instructionId: item.instruction.id,
      payload: { instructionId: item.instruction.id },
      requiresRole: "clerk",
      summary: `Enviar 0.01 MXN a la cuenta terminada en ${lastFour(
        item.instruction.clabe,
      )} de ${item.supplier.legalName} y leer el CEP que Banxico publique para esa clave.`,
    };
  }

  return answer;
}

/** The week, in counts and in pesos, read off the run the screens render. */
function runAnswer(input: OfflineTurnInput): Answer {
  const { totals } = MOCK_RUN;
  const text =
    `Esta corrida trae ${totals.instructions} pagos por ${formatMoney(totals.amount)}. ` +
    `Se detuvieron ${totals.held + totals.toVerify} lineas por ${formatMoney(totals.stoppedAmount)}: ` +
    `${totals.held} retenidas y ${totals.toVerify} para verificar, y ${totals.released} quedaron listas por ` +
    `${formatMoney(totals.releasedAmount)}. ` +
    (totals.retroactive69bExposure > 0
      ? `De lo que ya se dedujo a proveedores que la lista 69-B nombra, el ISR y el IVA que se revierten suman ${formatMoney(
          totals.retroactive69bExposure,
        )}.`
      : "Ninguna publicacion de la lista 69-B ha tasado todavia a un proveedor de esta corrida.");

  return {
    text,
    toolCalls: [
      toolCall(
        input,
        1,
        "get_run",
        { runId: MOCK_RUN.id },
        {
          pagos: totals.instructions,
          importe: totals.amount,
          retenidas: totals.held,
          por_verificar: totals.toVerify,
          detenido: totals.stoppedAmount,
          exposicion_retroactiva: totals.retroactive69bExposure,
        },
      ),
    ],
  };
}

/** What we have paid this supplier, and on which account. */
function supplierAnswer(item: PaymentRunItem, input: OfflineTurnInput): Answer {
  const accounts = item.supplier.knownAccounts;
  const known = accounts[0];
  const proposed = item.instruction.clabe;
  const isKnown = accounts.some((account) => account.clabe === proposed);

  const text =
    known === undefined
      ? `A ${item.supplier.legalName} nunca le hemos pagado: no hay ninguna cuenta suya en el expediente, asi que la de esta instruccion es nueva por definicion.`
      : `A ${item.supplier.legalName} le hemos pagado ${known.timesPaid} veces a la cuenta ${formatClabe(
          known.clabe,
        )}, que quedo establecida desde ${known.establishedAt.slice(0, 10)}. ` +
        (isKnown
          ? `La cuenta de esta instruccion es esa misma.`
          : `La de esta instruccion termina en ${lastFour(proposed)} y no esta en el expediente.`);

  const finding = leadFinding(item);

  return {
    text,
    instructionId: item.instruction.id,
    toolCalls: [
      toolCall(
        input,
        1,
        "get_instruction",
        { instructionId: item.instruction.id },
        finding === null
          ? {
              clabe: proposed,
              cuentas_conocidas: accounts.length,
            }
          : primitives(finding.evidence),
      ),
    ],
  };
}

/** Where the one-cent verification of this line stands. */
function verificationAnswer(
  item: PaymentRunItem,
  input: OfflineTurnInput,
): Answer {
  const verification = mockVerification(item.instruction.id);
  const state = verification?.state ?? "not_started";
  const result: Record<string, EvidenceValue> = { estado: state };

  if (verification?.claveRastreo) {
    result.clave_de_rastreo = verification.claveRastreo;
  }
  if (verification?.holderName) {
    result.titular = verification.holderName;
  }
  if (verification?.nameMatch) {
    result.comparacion_de_nombre = verification.nameMatch;
  }
  if (verification?.sealState) {
    result.sello = verification.sealState;
  }

  const answer: Answer = {
    text: `La verificacion de la cuenta de ${item.supplier.legalName} esta en "${VERIFICATION_LABEL[state].toLowerCase()}".`,
    instructionId: item.instruction.id,
    toolCalls: [
      toolCall(
        input,
        1,
        "get_verification",
        { instructionId: item.instruction.id },
        result,
      ),
    ],
  };

  if (state === "not_started") {
    answer.proposal = {
      kind: "verify_account",
      instructionId: item.instruction.id,
      payload: { instructionId: item.instruction.id },
      requiresRole: "clerk",
      summary: `Enviar 0.01 MXN a la cuenta terminada en ${lastFour(
        item.instruction.clabe,
      )} de ${item.supplier.legalName} y leer el CEP que Banxico publique para esa clave.`,
    };
  }

  return answer;
}

/**
 * The clerk asked to release a line a finding stopped, which is the one shape
 * `docs/02-persona.md` says the owner approves.
 *
 * The proposal comes back with `requiresRole: "owner"` and the panel will not send
 * it under a clerk's name. That is the role rule being visible on screen rather
 * than only in the API, and the reason box next to it is ADR-0007's mitigation for
 * a proposal somebody confirms while tired.
 */
function releaseAnswer(item: PaymentRunItem, input: OfflineTurnInput): Answer {
  const level = levelOf(item);
  const finding = leadFinding(item);

  const answer: Answer = {
    text:
      finding === null
        ? `Esta linea no tiene ningun hallazgo, asi que no hay excepcion que autorizar: su nivel es ${CONFIDENCE_LABEL[level.confidence].toLowerCase()} y su estado es ${STATE_LABEL[level.state].toLowerCase()}.`
        : `Liberar esta linea es una excepcion sobre un hallazgo abierto: ${finding.explanation} La autoriza el dueno y la razon queda escrita en el evento con su nombre.`,
    instructionId: item.instruction.id,
    toolCalls: [
      toolCall(
        input,
        1,
        "get_instruction",
        { instructionId: item.instruction.id },
        finding === null ? { hallazgos: 0 } : primitives(finding.evidence),
      ),
    ],
  };

  if (finding !== null) {
    answer.proposal = {
      kind: "decide",
      instructionId: item.instruction.id,
      payload: { action: "release" },
      requiresRole: "owner",
      summary: `Liberar el pago de ${item.supplier.legalName} por ${formatMoney(
        item.instruction.amount,
      )} sobre el hallazgo abierto, con la razon escrita y el nombre de quien lo autoriza.`,
    };
  }

  return answer;
}

/**
 * A screenshot was dropped, and there is no model in the browser to read it.
 *
 * So the answer says exactly that, and then shows what the extraction produces on
 * the server for the line this dataset carries: `INTAKE_EXAMPLE` is what
 * `POST /api/v1/instructions` answers for the WhatsApp message of the demo, and
 * the proposal's payload is that body field for field. The panel draws the file
 * the clerk actually dropped beside it, which is the half that is real offline:
 * the name, the media type and the size the browser reported.
 */
function intakeAnswer(): Answer {
  const example = mockIntakeExample();
  const { instruction, supplier } = example;

  return {
    text:
      `Sin conexion no se lee la imagen: la extraccion corre en la API, con el modelo que solo transcribe. ` +
      `Lo que traigo de la corrida sintetica para este caso es el mensaje de ${supplier.legalName} por ${formatMoney(
        instruction.amount,
      )} con la cuenta terminada en ${lastFour(instruction.clabe)}. ` +
      `Si lo das de alta, corren los seis controles y la linea aparece con su nivel y sus hallazgos.`,
    toolCalls: [],
    instructionId: instruction.id,
    proposal: {
      kind: "intake",
      payload: {
        amount: instruction.amount,
        source: instruction.source,
        clabe: instruction.clabe,
        supplierRfc: instruction.supplierRfc,
        ...(instruction.text === undefined ? {} : { text: instruction.text }),
      },
      requiresRole: "clerk",
      summary: `Dar de alta el pago de ${supplier.legalName} por ${formatMoney(
        instruction.amount,
      )} a la cuenta terminada en ${lastFour(instruction.clabe)} y correr los seis controles.`,
    },
  };
}

/** What this panel can answer with no API, which is not nothing. */
function helpAnswer(): Answer {
  return {
    text:
      "Sin conexion leo la corrida sintetica: por que se detuvo una linea, el resumen de la semana en pesos, " +
      "el historial de cuentas del proveedor y como va la verificacion de una cuenta. " +
      "Tambien puedes soltar una captura aqui y te preparo el alta.",
    toolCalls: [],
  };
}

/* ------------------------------------------------------------- the stream --- */

/** Four words at a time, so the offline answer arrives the way the API's does. */
export function tokenize(text: string, wordsPerToken = 4): string[] {
  const words = text.split(" ").filter((word) => word !== "");
  const tokens: string[] = [];

  for (let index = 0; index < words.length; index += wordsPerToken) {
    const chunk = words.slice(index, index + wordsPerToken).join(" ");

    tokens.push(index === 0 ? chunk : ` ${chunk}`);
  }

  return tokens;
}

/**
 * One whole offline turn as the five events of the contract, in the order the API
 * sends them: the reads first, then the answer as it is written, then at most one
 * proposal, then the stored turn.
 *
 * It is a pure function of the run and the question. The panel is what spaces the
 * events out in time, and it collapses the spacing to nothing when the system asks
 * for reduced motion, which is also what makes a screenshot reproducible.
 */
export function offlineTurn(input: OfflineTurnInput): AssistantStreamEvent[] {
  const answer = answerFor(input);
  const events: AssistantStreamEvent[] = [];

  for (const call of answer.toolCalls) {
    const started: AssistantToolCall = {
      id: call.id,
      tool: call.tool,
      arguments: call.arguments,
      at: call.at,
      readOnly: true,
    };

    events.push({ kind: "tool_call", call: started });
    events.push({ kind: "tool_result", call });
  }

  for (const text of tokenize(answer.text)) {
    events.push({ kind: "token", text });
  }

  if (answer.proposal !== undefined) {
    events.push({ kind: "proposal", proposal: answer.proposal });
  }

  const message: AssistantMessage = {
    id: `${input.sessionId}-${input.seq}`,
    sessionId: input.sessionId,
    author: "assistant",
    text: answer.text,
    at: input.at,
  };

  if (answer.instructionId !== undefined) {
    message.instructionId = answer.instructionId;
  }
  if (answer.toolCalls.length > 0) {
    message.toolCalls = answer.toolCalls;
  }
  if (answer.proposal !== undefined) {
    message.proposal = answer.proposal;
  }

  events.push({ kind: "done", message });

  return events;
}

/* -------------------------------------------------------- the confirmation --- */

/**
 * What a confirmed proposal shows with no API, and it is never a write.
 *
 * `?data=mock` promises that no request leaves the browser, so the panel cannot
 * call the endpoint and must not pretend it did. Two of the five proposals have an
 * answer in the dataset and they are the two the demo uses: the one-cent
 * verification of a line is the `VerificationState` the generator folded for it,
 * and the intake is the `InstructionDetail` the API answers for that message. The
 * panel renders them under a sentence saying nothing was written.
 */
export type OfflineConfirmation =
  | { kind: "verify_account"; verification: VerificationState }
  | { kind: "intake"; detail: InstructionDetail }
  | { kind: "none" };

export function offlineConfirm(proposal: ActionProposal): OfflineConfirmation {
  if (proposal.kind === "intake") {
    return { kind: "intake", detail: mockIntakeExample() };
  }

  if (proposal.kind === "verify_account") {
    const id =
      proposal.instructionId ??
      (typeof proposal.payload.instructionId === "string"
        ? proposal.payload.instructionId
        : null);
    const verification = id === null ? null : mockVerification(id);

    if (verification !== null) {
      return { kind: "verify_account", verification };
    }
  }

  return { kind: "none" };
}
